# Generated by Django 4.2.16 on 2024-12-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedetail',
            name='note',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
