# Generated by Django 4.2.16 on 2024-12-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancedetail_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedetail',
            name='note',
            field=models.TextField(default='Empty Message'),
        ),
    ]
