# Generated by Django 4.2.14 on 2025-01-28 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='priority_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='task_type',
            fields=[
                ('tasktype_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name', models.CharField(max_length=200)),
                ('ticket_type', models.CharField(max_length=200, null=True)),
                ('date_opened', models.DateField(null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('short_description', models.CharField(max_length=200, null=True)),
                ('comments', models.CharField(max_length=200, null=True)),
                ('user_comments', models.CharField(max_length=200, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer_contact')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.priority_type')),
            ],
        ),
        migrations.CreateModel(
            name='ticket_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('detail', models.CharField(max_length=300, null=True)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.ticket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
