# Generated by Django 4.2.20 on 2025-07-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_salaried_profile_wages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('User', 'User')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wages',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
