# Generated by Django 4.2.20 on 2025-07-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Assistant Developer', 'Assistant Developer'), ('Senior Developer', 'Senior Developer'), ('Operational Manager', 'Operational Manager'), ('CEO', 'CEO'), ('CFO', 'CFO'), ('CTO', 'CTO'), ('HR Manager', 'HR Manager'), ('Team Lead', 'Team Lead'), ('Intern', 'Intern')], default='Developer', max_length=30),
        ),
    ]
