# Generated by Django 4.2.14 on 2025-02-20 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0025_ticket_project_alter_ticket_closed_date_and_more'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='worklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('detail', models.CharField(max_length=200, null=True)),
                ('hours', models.IntegerField(null=True)),
                ('billable', models.BooleanField(null=True)),
                ('note', models.CharField(default='', max_length=200, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('week', models.CharField(max_length=100)),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.priority_type')),
                ('project_support', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worklog_project_support', to='project.project')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worklog_ticket', to='task.ticket')),
                ('ticket_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worklog_ticket_type', to='task.ticket_type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
