# Generated by Django 4.2.18 on 2025-01-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
    ]
