# Generated by Django 4.2.17 on 2025-03-11 04:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worklog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_note', models.CharField(blank=True, max_length=300, null=True)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('send_to', models.ManyToManyField(related_name='worklog_send_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
