# Generated by Django 4.2.20 on 2025-07-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0003_alter_worklog_workdone_mailnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='worklog',
            name='workdone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
