# Generated by Django 4.2.20 on 2025-07-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0004_status_alter_worklog_workdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='workdone',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
