# Generated by Django 4.2.20 on 2025-07-31 07:09

from django.db import migrations, models
import django.db.models.deletion
import worklog.models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0005_alter_worklog_workdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='status',
            field=models.ForeignKey(default=worklog.models.get_default_status, on_delete=django.db.models.deletion.CASCADE, to='worklog.status'),
        ),
    ]
