# Generated by Django 4.2.14 on 2025-02-24 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0003_customer_status_alter_customer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='priority_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('date_opened', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ticket_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=200)),
                ('ticket_title', models.CharField(max_length=200)),
                ('date_opened', models.DateField(null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('operational_notes', models.CharField(max_length=200, null=True)),
                ('closed_date', models.DateField(null=True)),
                ('solution', models.TextField(max_length=500)),
                ('assigned_to', models.ManyToManyField(related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.priority_type')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.project')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.state')),
                ('ticket_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.ticket_type')),
            ],
        ),
        migrations.CreateModel(
            name='subproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_project_id', models.CharField(max_length=200)),
                ('sub_project_name', models.CharField(max_length=200)),
                ('date_opened', models.DateField(null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.project')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
