# Generated by Django 4.2.14 on 2025-02-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_opened',
            field=models.DateTimeField(null=True),
        ),
    ]
