# Generated by Django 4.2.18 on 2025-01-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_ticket_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='state',
        ),
    ]
