# Generated by Django 4.2.14 on 2025-02-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_ticket_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='closed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
