# Generated by Django 4.2.16 on 2025-01-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_ticket_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
