# Generated by Django 4.2.16 on 2025-01-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_ticket_comments_alter_ticket_user_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user_comments',
            field=models.CharField(default='', max_length=200),
        ),
    ]
