# Generated by Django 4.2.17 on 2025-02-03 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0010_alter_ticket_user_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket_update_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(null=True)),
                ('changes', models.CharField(max_length=500, null=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_name',
            new_name='ticket_title',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user_comments',
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solution',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default='m', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ticket_detail',
        ),
    ]
