# Generated by Django 4.2.16 on 2025-02-04 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0012_remove_ticket_assigned_to_ticket_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
