# Generated by Django 4.2.14 on 2025-02-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ticket_update_history',
        ),
    ]
