# Generated by Django 4.2.14 on 2025-02-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_delete_ticket_update_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='solution',
            field=models.TextField(default='', max_length=500),
        ),
    ]
