# Generated by Django 4.2.14 on 2025-02-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_alter_ticket_solution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='short_description',
            new_name='operational_notes',
        ),
    ]
