# Generated by Django 4.2.14 on 2025-02-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_rename_short_description_ticket_operational_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='solution',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
