# Generated by Django 4.2.14 on 2025-02-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_alter_ticket_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='solution',
            field=models.TextField(default='Enter solution', max_length=500),
        ),
    ]
