# Generated by Django 4.2.14 on 2025-02-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_alter_ticket_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='solution',
            field=models.TextField(default='', max_length=500, null=True),
        ),
    ]
