# Generated by Django 4.2.14 on 2025-02-14 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0003_customer_status_alter_customer_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('estimated_hr', models.IntegerField(null=True)),
                ('completed_hr', models.IntegerField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('estimated_complete_date', models.DateField(null=True)),
                ('actual_complete_date', models.DateField(null=True)),
                ('assigned_to', models.ManyToManyField(related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
