# Generated by Django 4.2.20 on 2025-07-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavedetails',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='leavedetails',
            name='remarks',
            field=models.TextField(default=''),
        ),
    ]
