# Generated by Django 4.2.20 on 2025-07-09 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0002_leavedetails_description_leavedetails_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavedetails',
            name='approvedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ApprovedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavedetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RequestedUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='userLeaveDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveTaken', models.IntegerField()),
                ('availableDays', models.IntegerField(blank=True, null=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.leavetype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
