# Generated by Django 4.2.23 on 2025-07-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_earnedleaveday_earned_leave_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earnedleaveday',
            name='joined_date',
        ),
    ]
