# Generated by Django 4.2.23 on 2025-07-13 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_earnedleaveday_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnedleaveday',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
