# Generated by Django 4.2.20 on 2025-07-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_earnedleaveday_joined_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='days',
        ),
        migrations.RemoveField(
            model_name='userleavedays',
            name='availableDays',
        ),
    ]
