# Generated by Django 4.2.20 on 2025-07-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_leavetype_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavedays',
            name='leaveTaken',
            field=models.IntegerField(default=0),
        ),
    ]
