# Generated by Django 4.2.20 on 2025-07-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_userleavedays_leavetaken'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavedetails',
            name='exceededdays',
            field=models.IntegerField(default=0),
        ),
    ]
