# Generated by Django 4.2.20 on 2025-07-21 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_leavedetails_exceededdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavedetails',
            name='approval',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.approval'),
        ),
    ]
