# Generated by Django 4.2.14 on 2025-02-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_subproject_sub_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subproject',
            old_name='project_id',
            new_name='project',
        ),
    ]
